cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}

path:
  data: /data
  logs: /data/log
  plugins: ${ES_INSTALL}/plugins
  work: ${ES_INSTALL}/work

bootstrap.mlockall: true

http.enabled: ${HTTP_ENABLE}
cloud.enabled: ${CLOUD_ENABLE}

index:
  store:
    type: niofs

repositories:
  s3:
    bucket: ${S3_BUCKET}
    region: ${S3_REGION}
    access_key: ${S3_ACCESS_KEY}
    secret_key: ${S3_SECRET_KEY}

cloud:
  k8s:
    service: ${DISCOVERY_SERVICE}
    namespace: ${NAMESPACE}
discovery:
  type: io.fabric8.elasticsearch.discovery.k8s.K8sDiscoveryModule
  zen.ping.multicast.enabled: false
