---
cluster.name: ${CLUSTER_NAME}

node.name: ${NODE_NAME}
node.master: ${NODE_MASTER}
node.data: ${NODE_DATA}

path.data: ${PATH_DATA}
path.logs: ${PATH_DATA}/logs

bootstrap.mlockall: true
security.manager.enabled: false

network.host: 0.0.0.0

index.auto_expand_replicas: ${INDEX_AUTO_EXPAND_REPLICAS}

http.enabled: ${HTTP_ENABLE}
http.compression: true
http.cors.enabled: true

cloud.kubernetes.service: ${KUBERNETES_SERVICE}
cloud.kubernetes.namespace: ${KUBERNETES_NAMESPACE}
discovery.type: kubernetes
discovery.zen.ping.multicast.enabled: false
