cluster:
  name: ${CLUSTER_NAME}

node:
  name: ${NODE_NAME}
  master: ${NODE_MASTER}
  data: ${NODE_DATA}

path:
  data: /data
  logs: /data/log
  plugins: ${ES_INSTALL}/plugins
  work: ${ES_INSTALL}/work

index.store.type: ${INDEX_STORE_TYPE}

bootstrap.mlockall: true

http.enabled: ${HTTP_ENABLE}
cloud.enabled: ${CLOUD_ENABLE}

cloud:
  k8s:
    service: ${DISCOVERY_SERVICE}
    namespace: ${NAMESPACE}
discovery:
  type: io.fabric8.elasticsearch.discovery.k8s.K8sDiscoveryModule
  zen.ping.multicast.enabled: false
